using System.Collections.Generic;
using System.Linq;

namespace RoboCopyElite.Core.Options;

/// <summary>
/// Central registry of every supported robocopy switch. Keeping this deterministic ensures command building is repeatable.
/// </summary>
public static class OptionRegistry
{
    private static readonly IReadOnlyList<OptionDefinition> AllOptions = new List<OptionDefinition>
    {
        new("/S", "Copy Subdirectories (non-empty)", OptionCategory.Basic),
        new("/E", "Copy Subdirectories (including empty)", OptionCategory.Basic),
        new("/LEV", "Copy Top Levels", OptionCategory.Basic, OptionArgumentKind.Integer, "Copy only the top N levels of the source directory tree.", "N", RequiresValue: true),
        new("/Z", "Restartable Mode", OptionCategory.Basic),
        new("/B", "Backup Mode", OptionCategory.Security, IsDangerous: true),
        new("/ZB", "Restartable then Backup", OptionCategory.Security, IsDangerous: true),
        new("/J", "Unbuffered I/O", OptionCategory.Performance),
        new("/EFSRAW", "Copy EFS Raw", OptionCategory.Security, IsDangerous: true),
        new("/COPY", "Copy File Data", OptionCategory.Security, OptionArgumentKind.SwitchList, "Specifies the file properties to copy.", "DATSOU", AllowsMultiple: true, RequiresValue: true),
        new("/DCOPY", "Copy Directory Info", OptionCategory.Security, OptionArgumentKind.SwitchList, "Copy directory data, attributes, time stamps, owner, and ACLs.", "DAST", RequiresValue: true),
        new("/SEC", "Copy Security", OptionCategory.Security),
        new("/COPYALL", "Copy All", OptionCategory.Security),
        new("/NOCOPY", "Do Not Copy File Info", OptionCategory.Advanced, IsDangerous: true),
        new("/SECFIX", "Fix Security on Existing Files", OptionCategory.Security),
        new("/TIMFIX", "Fix Timestamps on Existing Files", OptionCategory.Security),
        new("/PURGE", "Purge Destination of Orphaned Files", OptionCategory.Advanced, IsDangerous: true),
        new("/MIR", "Mirror Directory Tree", OptionCategory.Advanced, IsDangerous: true),
        new("/MOV", "Move Files Only", OptionCategory.Advanced, IsDangerous: true),
        new("/MOVE", "Move Files and Directories", OptionCategory.Advanced, IsDangerous: true),
        new("/A+", "Add Attributes", OptionCategory.Advanced, OptionArgumentKind.SwitchList, RequiresValue: true),
        new("/A-", "Remove Attributes", OptionCategory.Advanced, OptionArgumentKind.SwitchList, RequiresValue: true),
        new("/CREATE", "Create Directory Tree and Zero-Length Files", OptionCategory.Advanced),
        new("/FAT", "Use Fat File Timestamps", OptionCategory.Advanced),
        new("/256", "Disable Long Paths", OptionCategory.Advanced),
        new("/MON", "Monitor Changes Count", OptionCategory.Advanced, OptionArgumentKind.Integer, "Run until N changes are seen.", "N", RequiresValue: true),
        new("/MOT", "Monitor Changes Time", OptionCategory.Advanced, OptionArgumentKind.Integer, "Run every N minutes.", "M", RequiresValue: true),
        new("/RH", "Run Hours", OptionCategory.Advanced, OptionArgumentKind.TimeWindow, "Run during the hours specified.", "hhmm-hhmm", RequiresValue: true),
        new("/PF", "Per-File Run Hours", OptionCategory.Advanced),
        new("/IPG", "Inter-Packet Gap", OptionCategory.Performance, OptionArgumentKind.Integer, "Throttle network I/O by waiting N milliseconds between packets.", "ms", RequiresValue: true),
        new("/SJ", "Skip Junctions", OptionCategory.Filters),
        new("/SL", "Follow Symbolic Links", OptionCategory.Advanced),
        new("/MT", "Multi-Threaded Copies", OptionCategory.Performance, OptionArgumentKind.Integer, "Use N threads (1-128).", "N", RequiresValue: true),
        new("/NODCOPY", "Disable Directory Copy", OptionCategory.Advanced),
        new("/NOOFFLOAD", "Disable Offloaded Copies", OptionCategory.Performance),
        new("/COMPRESS", "Enable Windows Compression", OptionCategory.Performance),
        new("/SPARSE", "Create Sparse Files", OptionCategory.Advanced),
        new("/NOCLONE", "Disable Clonefile", OptionCategory.Performance),
        new("/IOMAXSIZE", "I/O Max Request Size", OptionCategory.Performance, OptionArgumentKind.SizeWithSuffix, "Maximum I/O request size (supports K/M/G).", "bytes", RequiresValue: true),
        new("/IORATE", "I/O Rate Throttle", OptionCategory.Performance, OptionArgumentKind.SizeWithSuffix, "Throttle I/O rate with K/M/G suffix.", "bytes/sec", RequiresValue: true),
        new("/THRESHOLD", "I/O Threshold", OptionCategory.Performance, OptionArgumentKind.SizeWithSuffix, "Switch to unbuffered I/O for files above threshold.", "bytes", RequiresValue: true),
        new("/A", "Copy Only Files with Archive Attribute Set", OptionCategory.Filters),
        new("/M", "Copy and Reset Archive Attribute", OptionCategory.Filters),
        new("/IA", "Include Attributes", OptionCategory.Filters, OptionArgumentKind.SwitchList, RequiresValue: true),
        new("/XA", "Exclude Attributes", OptionCategory.Filters, OptionArgumentKind.SwitchList, RequiresValue: true),
        new("/XF", "Exclude Files", OptionCategory.Filters, OptionArgumentKind.String, "File patterns to exclude.", "files", AllowsMultiple: true, RequiresValue: true),
        new("/XD", "Exclude Directories", OptionCategory.Filters, OptionArgumentKind.String, "Directory patterns to exclude.", "dirs", AllowsMultiple: true, RequiresValue: true),
        new("/XC", "Exclude Changed Files", OptionCategory.Filters),
        new("/XN", "Exclude Newer Files", OptionCategory.Filters),
        new("/XO", "Exclude Older Files", OptionCategory.Filters),
        new("/XX", "Exclude Extra Files and Dirs", OptionCategory.Filters),
        new("/XL", "Exclude Lonely Files and Dirs", OptionCategory.Filters),
        new("/IM", "Include Modified Files", OptionCategory.Filters),
        new("/IS", "Include Same Files", OptionCategory.Filters),
        new("/IT", "Include Tweaked Files", OptionCategory.Filters),
        new("/MAX", "Maximum File Size", OptionCategory.Filters, OptionArgumentKind.SizeWithSuffix, RequiresValue: true),
        new("/MIN", "Minimum File Size", OptionCategory.Filters, OptionArgumentKind.SizeWithSuffix, RequiresValue: true),
        new("/MAXAGE", "Maximum File Age", OptionCategory.Filters, OptionArgumentKind.Integer, "Maximum file age in days or YYYYMMDD.", "age", RequiresValue: true),
        new("/MINAGE", "Minimum File Age", OptionCategory.Filters, OptionArgumentKind.Integer, "Minimum file age in days or YYYYMMDD.", "age", RequiresValue: true),
        new("/MAXLAD", "Maximum Last Access Date", OptionCategory.Filters, OptionArgumentKind.Integer, RequiresValue: true),
        new("/MINLAD", "Minimum Last Access Date", OptionCategory.Filters, OptionArgumentKind.Integer, RequiresValue: true),
        new("/XJ", "Exclude Junction Points", OptionCategory.Filters),
        new("/FFT", "Assume FAT File Times", OptionCategory.Filters),
        new("/DST", "Compensate for Daylight Saving", OptionCategory.Filters),
        new("/XJD", "Exclude Junctions for Directories", OptionCategory.Filters),
        new("/XJF", "Exclude Junctions for Files", OptionCategory.Filters),
        new("/R", "Number of Retries", OptionCategory.Basic, OptionArgumentKind.Integer, "Set retry count for failures.", "N", RequiresValue: true),
        new("/W", "Wait Between Retries", OptionCategory.Basic, OptionArgumentKind.Integer, "Seconds to wait between retries.", "N", RequiresValue: true),
        new("/REG", "Save Retry Settings", OptionCategory.Basic),
        new("/TBD", "Wait for Share Names", OptionCategory.Basic),
        new("/LFSM", "Low Free Space Mode", OptionCategory.Performance, OptionArgumentKind.Integer, "Enable LFSM with threshold in MB.", "MB", RequiresValue: true),
        new("/L", "List Only (Dry Run)", OptionCategory.Logging),
        new("/X", "Report Extra Files", OptionCategory.Logging),
        new("/V", "Verbose Output", OptionCategory.Logging),
        new("/TS", "Include Source File Timestamp", OptionCategory.Logging),
        new("/FP", "Include Full Path Names", OptionCategory.Logging),
        new("/BYTES", "Log Byte Sizes", OptionCategory.Logging),
        new("/NS", "No Size Information", OptionCategory.Logging),
        new("/NC", "No Class Information", OptionCategory.Logging),
        new("/NFL", "No File List", OptionCategory.Logging),
        new("/NDL", "No Directory List", OptionCategory.Logging),
        new("/NP", "No Progress", OptionCategory.Logging),
        new("/ETA", "Show Estimated Time of Arrival", OptionCategory.Logging),
        new("/LOG", "Log to File", OptionCategory.Logging, OptionArgumentKind.Path, "Write log to file (overwrite).", "path", RequiresValue: true),
        new("/LOG+", "Log to File (Append)", OptionCategory.Logging, OptionArgumentKind.Path, "Append log to file.", "path", RequiresValue: true),
        new("/UNILOG", "Unicode Log", OptionCategory.Logging, OptionArgumentKind.Path, "Write Unicode log (overwrite).", "path", RequiresValue: true),
        new("/UNILOG+", "Unicode Log Append", OptionCategory.Logging, OptionArgumentKind.Path, "Append Unicode log.", "path", RequiresValue: true),
        new("/TEE", "Output to Console and Log", OptionCategory.Logging),
        new("/NJH", "No Job Header", OptionCategory.Logging),
        new("/NJS", "No Job Summary", OptionCategory.Logging),
        new("/UNICODE", "Unicode Output", OptionCategory.Logging),
        new("/SAVE", "Save Job File", OptionCategory.Jobs, OptionArgumentKind.Path, RequiresValue: true),
        new("/JOB", "Run Job File", OptionCategory.Jobs, OptionArgumentKind.Path, RequiresValue: true),
        new("/QUIT", "Quit After Processing Command Line", OptionCategory.Jobs),
        new("/NOSD", "No Source Directory", OptionCategory.Jobs),
        new("/NODD", "No Destination Directory", OptionCategory.Jobs),
        new("/IF", "Include Files", OptionCategory.Filters),
        new("/PFN", "Full Path File Names", OptionCategory.Logging),
    };

    public static IReadOnlyList<OptionDefinition> GetAll() => AllOptions;

    public static OptionDefinition? TryGet(string switchName)
    {
        return AllOptions.FirstOrDefault(o => string.Equals(o.Switch, switchName, System.StringComparison.OrdinalIgnoreCase));
    }
}
